/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WindowDotscreenRouteImport } from './routes/window[.]screen'
import { Route as WindowDotgetScreenDetailsRouteImport } from './routes/window[.]getScreenDetails()'
import { Route as NavigatorDotstorageDotestimateRouteImport } from './routes/navigator[.]storage[.]estimate()'
import { Route as NavigatorDotstorageRouteImport } from './routes/navigator[.]storage'
import { Route as NavigatorDotkeyboardDotgetLayoutMapRouteImport } from './routes/navigator[.]keyboard[.]getLayoutMap()'
import { Route as NavigatorDotkeyboardRouteImport } from './routes/navigator[.]keyboard'
import { Route as NavigatorDotgetBatteryRouteImport } from './routes/navigator[.]getBattery()'
import { Route as MathDotrandomRouteImport } from './routes/Math[.]random()'
import { Route as IndexRouteImport } from './routes/index'

const WindowDotscreenRoute = WindowDotscreenRouteImport.update({
  id: '/window.screen',
  path: '/window.screen',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowDotgetScreenDetailsRoute =
  WindowDotgetScreenDetailsRouteImport.update({
    id: '/window.getScreenDetails()',
    path: '/window.getScreenDetails()',
    getParentRoute: () => rootRouteImport,
  } as any)
const NavigatorDotstorageDotestimateRoute =
  NavigatorDotstorageDotestimateRouteImport.update({
    id: '/navigator.storage.estimate()',
    path: '/navigator.storage.estimate()',
    getParentRoute: () => rootRouteImport,
  } as any)
const NavigatorDotstorageRoute = NavigatorDotstorageRouteImport.update({
  id: '/navigator.storage',
  path: '/navigator.storage',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigatorDotkeyboardDotgetLayoutMapRoute =
  NavigatorDotkeyboardDotgetLayoutMapRouteImport.update({
    id: '/navigator.keyboard.getLayoutMap()',
    path: '/navigator.keyboard.getLayoutMap()',
    getParentRoute: () => rootRouteImport,
  } as any)
const NavigatorDotkeyboardRoute = NavigatorDotkeyboardRouteImport.update({
  id: '/navigator.keyboard',
  path: '/navigator.keyboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigatorDotgetBatteryRoute = NavigatorDotgetBatteryRouteImport.update({
  id: '/navigator.getBattery()',
  path: '/navigator.getBattery()',
  getParentRoute: () => rootRouteImport,
} as any)
const MathDotrandomRoute = MathDotrandomRouteImport.update({
  id: '/Math.random()',
  path: '/Math.random()',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Math.random()': typeof MathDotrandomRoute
  '/navigator.getBattery()': typeof NavigatorDotgetBatteryRoute
  '/navigator.keyboard': typeof NavigatorDotkeyboardRoute
  '/navigator.keyboard.getLayoutMap()': typeof NavigatorDotkeyboardDotgetLayoutMapRoute
  '/navigator.storage': typeof NavigatorDotstorageRoute
  '/navigator.storage.estimate()': typeof NavigatorDotstorageDotestimateRoute
  '/window.getScreenDetails()': typeof WindowDotgetScreenDetailsRoute
  '/window.screen': typeof WindowDotscreenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Math.random()': typeof MathDotrandomRoute
  '/navigator.getBattery()': typeof NavigatorDotgetBatteryRoute
  '/navigator.keyboard': typeof NavigatorDotkeyboardRoute
  '/navigator.keyboard.getLayoutMap()': typeof NavigatorDotkeyboardDotgetLayoutMapRoute
  '/navigator.storage': typeof NavigatorDotstorageRoute
  '/navigator.storage.estimate()': typeof NavigatorDotstorageDotestimateRoute
  '/window.getScreenDetails()': typeof WindowDotgetScreenDetailsRoute
  '/window.screen': typeof WindowDotscreenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Math.random()': typeof MathDotrandomRoute
  '/navigator.getBattery()': typeof NavigatorDotgetBatteryRoute
  '/navigator.keyboard': typeof NavigatorDotkeyboardRoute
  '/navigator.keyboard.getLayoutMap()': typeof NavigatorDotkeyboardDotgetLayoutMapRoute
  '/navigator.storage': typeof NavigatorDotstorageRoute
  '/navigator.storage.estimate()': typeof NavigatorDotstorageDotestimateRoute
  '/window.getScreenDetails()': typeof WindowDotgetScreenDetailsRoute
  '/window.screen': typeof WindowDotscreenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Math.random()'
    | '/navigator.getBattery()'
    | '/navigator.keyboard'
    | '/navigator.keyboard.getLayoutMap()'
    | '/navigator.storage'
    | '/navigator.storage.estimate()'
    | '/window.getScreenDetails()'
    | '/window.screen'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Math.random()'
    | '/navigator.getBattery()'
    | '/navigator.keyboard'
    | '/navigator.keyboard.getLayoutMap()'
    | '/navigator.storage'
    | '/navigator.storage.estimate()'
    | '/window.getScreenDetails()'
    | '/window.screen'
  id:
    | '__root__'
    | '/'
    | '/Math.random()'
    | '/navigator.getBattery()'
    | '/navigator.keyboard'
    | '/navigator.keyboard.getLayoutMap()'
    | '/navigator.storage'
    | '/navigator.storage.estimate()'
    | '/window.getScreenDetails()'
    | '/window.screen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MathDotrandomRoute: typeof MathDotrandomRoute
  NavigatorDotgetBatteryRoute: typeof NavigatorDotgetBatteryRoute
  NavigatorDotkeyboardRoute: typeof NavigatorDotkeyboardRoute
  NavigatorDotkeyboardDotgetLayoutMapRoute: typeof NavigatorDotkeyboardDotgetLayoutMapRoute
  NavigatorDotstorageRoute: typeof NavigatorDotstorageRoute
  NavigatorDotstorageDotestimateRoute: typeof NavigatorDotstorageDotestimateRoute
  WindowDotgetScreenDetailsRoute: typeof WindowDotgetScreenDetailsRoute
  WindowDotscreenRoute: typeof WindowDotscreenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/window.screen': {
      id: '/window.screen'
      path: '/window.screen'
      fullPath: '/window.screen'
      preLoaderRoute: typeof WindowDotscreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window.getScreenDetails()': {
      id: '/window.getScreenDetails()'
      path: '/window.getScreenDetails()'
      fullPath: '/window.getScreenDetails()'
      preLoaderRoute: typeof WindowDotgetScreenDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigator.storage.estimate()': {
      id: '/navigator.storage.estimate()'
      path: '/navigator.storage.estimate()'
      fullPath: '/navigator.storage.estimate()'
      preLoaderRoute: typeof NavigatorDotstorageDotestimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigator.storage': {
      id: '/navigator.storage'
      path: '/navigator.storage'
      fullPath: '/navigator.storage'
      preLoaderRoute: typeof NavigatorDotstorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigator.keyboard.getLayoutMap()': {
      id: '/navigator.keyboard.getLayoutMap()'
      path: '/navigator.keyboard.getLayoutMap()'
      fullPath: '/navigator.keyboard.getLayoutMap()'
      preLoaderRoute: typeof NavigatorDotkeyboardDotgetLayoutMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigator.keyboard': {
      id: '/navigator.keyboard'
      path: '/navigator.keyboard'
      fullPath: '/navigator.keyboard'
      preLoaderRoute: typeof NavigatorDotkeyboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigator.getBattery()': {
      id: '/navigator.getBattery()'
      path: '/navigator.getBattery()'
      fullPath: '/navigator.getBattery()'
      preLoaderRoute: typeof NavigatorDotgetBatteryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Math.random()': {
      id: '/Math.random()'
      path: '/Math.random()'
      fullPath: '/Math.random()'
      preLoaderRoute: typeof MathDotrandomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MathDotrandomRoute: MathDotrandomRoute,
  NavigatorDotgetBatteryRoute: NavigatorDotgetBatteryRoute,
  NavigatorDotkeyboardRoute: NavigatorDotkeyboardRoute,
  NavigatorDotkeyboardDotgetLayoutMapRoute:
    NavigatorDotkeyboardDotgetLayoutMapRoute,
  NavigatorDotstorageRoute: NavigatorDotstorageRoute,
  NavigatorDotstorageDotestimateRoute: NavigatorDotstorageDotestimateRoute,
  WindowDotgetScreenDetailsRoute: WindowDotgetScreenDetailsRoute,
  WindowDotscreenRoute: WindowDotscreenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
