/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WindowDotvisualViewportRouteImport } from './routes/window[.]visualViewport'
import { Route as WindowDotviewportRouteImport } from './routes/window[.]viewport'
import { Route as WindowDotscreenRouteImport } from './routes/window[.]screen'
import { Route as WindowDotqueryLocalFontsRouteImport } from './routes/window[.]queryLocalFonts()'
import { Route as WindowDotperformanceRouteImport } from './routes/window[.]performance'
import { Route as WindowDotgetScreenDetailsRouteImport } from './routes/window[.]getScreenDetails()'
import { Route as WindowRouteImport } from './routes/window'
import { Route as UseRouterStateRouteImport } from './routes/useRouterState()'
import { Route as UseRouterRouteImport } from './routes/useRouter()'
import { Route as UseLocationRouteImport } from './routes/useLocation()'
import { Route as NavigatorDotwakeLockRouteImport } from './routes/navigator[.]wakeLock'
import { Route as NavigatorDotuserActivationRouteImport } from './routes/navigator[.]userActivation'
import { Route as NavigatorDotstorageDotestimateRouteImport } from './routes/navigator[.]storage[.]estimate()'
import { Route as NavigatorDotstorageRouteImport } from './routes/navigator[.]storage'
import { Route as NavigatorDotshareRouteImport } from './routes/navigator[.]share()'
import { Route as NavigatorDotonLineRouteImport } from './routes/navigator[.]onLine'
import { Route as NavigatorDotmediaDevicesDotgetSupportedConstraintsRouteImport } from './routes/navigator[.]mediaDevices[.]getSupportedConstraints()'
import { Route as NavigatorDotmediaDevicesDotenumerateDevicesRouteImport } from './routes/navigator[.]mediaDevices[.]enumerateDevices()'
import { Route as NavigatorDotmediaDevicesRouteImport } from './routes/navigator[.]mediaDevices'
import { Route as NavigatorDotkeyboardDotgetLayoutMapRouteImport } from './routes/navigator[.]keyboard[.]getLayoutMap()'
import { Route as NavigatorDotkeyboardRouteImport } from './routes/navigator[.]keyboard'
import { Route as NavigatorDotgetBatteryRouteImport } from './routes/navigator[.]getBattery()'
import { Route as NavigatorDotgeolocationDotgetCurrentPositionRouteImport } from './routes/navigator[.]geolocation[.]getCurrentPosition()'
import { Route as NavigatorDotconnectionRouteImport } from './routes/navigator[.]connection'
import { Route as NavigatorDotclipboardRouteImport } from './routes/navigator[.]clipboard'
import { Route as NavigatorRouteImport } from './routes/navigator'
import { Route as DocumentDotfeaturePolicyDotfeaturesRouteImport } from './routes/document[.]featurePolicy[.]features()'
import { Route as DocumentDotfeaturePolicyDotallowedFeaturesRouteImport } from './routes/document[.]featurePolicy[.]allowedFeatures()'
import { Route as DocumentDotfeaturePolicyRouteImport } from './routes/document[.]featurePolicy'
import { Route as DocumentRouteImport } from './routes/document'
import { Route as MathDotrandomRouteImport } from './routes/Math[.]random()'
import { Route as ImageRouteImport } from './routes/Image()'
import { Route as IndexRouteImport } from './routes/index'

const WindowDotvisualViewportRoute = WindowDotvisualViewportRouteImport.update({
  id: '/window.visualViewport',
  path: '/window.visualViewport',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowDotviewportRoute = WindowDotviewportRouteImport.update({
  id: '/window.viewport',
  path: '/window.viewport',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowDotscreenRoute = WindowDotscreenRouteImport.update({
  id: '/window.screen',
  path: '/window.screen',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowDotqueryLocalFontsRoute =
  WindowDotqueryLocalFontsRouteImport.update({
    id: '/window.queryLocalFonts()',
    path: '/window.queryLocalFonts()',
    getParentRoute: () => rootRouteImport,
  } as any)
const WindowDotperformanceRoute = WindowDotperformanceRouteImport.update({
  id: '/window.performance',
  path: '/window.performance',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowDotgetScreenDetailsRoute =
  WindowDotgetScreenDetailsRouteImport.update({
    id: '/window.getScreenDetails()',
    path: '/window.getScreenDetails()',
    getParentRoute: () => rootRouteImport,
  } as any)
const WindowRoute = WindowRouteImport.update({
  id: '/window',
  path: '/window',
  getParentRoute: () => rootRouteImport,
} as any)
const UseRouterStateRoute = UseRouterStateRouteImport.update({
  id: '/useRouterState()',
  path: '/useRouterState()',
  getParentRoute: () => rootRouteImport,
} as any)
const UseRouterRoute = UseRouterRouteImport.update({
  id: '/useRouter()',
  path: '/useRouter()',
  getParentRoute: () => rootRouteImport,
} as any)
const UseLocationRoute = UseLocationRouteImport.update({
  id: '/useLocation()',
  path: '/useLocation()',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigatorDotwakeLockRoute = NavigatorDotwakeLockRouteImport.update({
  id: '/navigator.wakeLock',
  path: '/navigator.wakeLock',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigatorDotuserActivationRoute =
  NavigatorDotuserActivationRouteImport.update({
    id: '/navigator.userActivation',
    path: '/navigator.userActivation',
    getParentRoute: () => rootRouteImport,
  } as any)
const NavigatorDotstorageDotestimateRoute =
  NavigatorDotstorageDotestimateRouteImport.update({
    id: '/navigator.storage.estimate()',
    path: '/navigator.storage.estimate()',
    getParentRoute: () => rootRouteImport,
  } as any)
const NavigatorDotstorageRoute = NavigatorDotstorageRouteImport.update({
  id: '/navigator.storage',
  path: '/navigator.storage',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigatorDotshareRoute = NavigatorDotshareRouteImport.update({
  id: '/navigator.share()',
  path: '/navigator.share()',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigatorDotonLineRoute = NavigatorDotonLineRouteImport.update({
  id: '/navigator.onLine',
  path: '/navigator.onLine',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigatorDotmediaDevicesDotgetSupportedConstraintsRoute =
  NavigatorDotmediaDevicesDotgetSupportedConstraintsRouteImport.update({
    id: '/navigator.mediaDevices.getSupportedConstraints()',
    path: '/navigator.mediaDevices.getSupportedConstraints()',
    getParentRoute: () => rootRouteImport,
  } as any)
const NavigatorDotmediaDevicesDotenumerateDevicesRoute =
  NavigatorDotmediaDevicesDotenumerateDevicesRouteImport.update({
    id: '/navigator.mediaDevices.enumerateDevices()',
    path: '/navigator.mediaDevices.enumerateDevices()',
    getParentRoute: () => rootRouteImport,
  } as any)
const NavigatorDotmediaDevicesRoute =
  NavigatorDotmediaDevicesRouteImport.update({
    id: '/navigator.mediaDevices',
    path: '/navigator.mediaDevices',
    getParentRoute: () => rootRouteImport,
  } as any)
const NavigatorDotkeyboardDotgetLayoutMapRoute =
  NavigatorDotkeyboardDotgetLayoutMapRouteImport.update({
    id: '/navigator.keyboard.getLayoutMap()',
    path: '/navigator.keyboard.getLayoutMap()',
    getParentRoute: () => rootRouteImport,
  } as any)
const NavigatorDotkeyboardRoute = NavigatorDotkeyboardRouteImport.update({
  id: '/navigator.keyboard',
  path: '/navigator.keyboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigatorDotgetBatteryRoute = NavigatorDotgetBatteryRouteImport.update({
  id: '/navigator.getBattery()',
  path: '/navigator.getBattery()',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigatorDotgeolocationDotgetCurrentPositionRoute =
  NavigatorDotgeolocationDotgetCurrentPositionRouteImport.update({
    id: '/navigator.geolocation.getCurrentPosition()',
    path: '/navigator.geolocation.getCurrentPosition()',
    getParentRoute: () => rootRouteImport,
  } as any)
const NavigatorDotconnectionRoute = NavigatorDotconnectionRouteImport.update({
  id: '/navigator.connection',
  path: '/navigator.connection',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigatorDotclipboardRoute = NavigatorDotclipboardRouteImport.update({
  id: '/navigator.clipboard',
  path: '/navigator.clipboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigatorRoute = NavigatorRouteImport.update({
  id: '/navigator',
  path: '/navigator',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentDotfeaturePolicyDotfeaturesRoute =
  DocumentDotfeaturePolicyDotfeaturesRouteImport.update({
    id: '/document.featurePolicy.features()',
    path: '/document.featurePolicy.features()',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocumentDotfeaturePolicyDotallowedFeaturesRoute =
  DocumentDotfeaturePolicyDotallowedFeaturesRouteImport.update({
    id: '/document.featurePolicy.allowedFeatures()',
    path: '/document.featurePolicy.allowedFeatures()',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocumentDotfeaturePolicyRoute =
  DocumentDotfeaturePolicyRouteImport.update({
    id: '/document.featurePolicy',
    path: '/document.featurePolicy',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocumentRoute = DocumentRouteImport.update({
  id: '/document',
  path: '/document',
  getParentRoute: () => rootRouteImport,
} as any)
const MathDotrandomRoute = MathDotrandomRouteImport.update({
  id: '/Math.random()',
  path: '/Math.random()',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageRoute = ImageRouteImport.update({
  id: '/Image()',
  path: '/Image()',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Image()': typeof ImageRoute
  '/Math.random()': typeof MathDotrandomRoute
  '/document': typeof DocumentRoute
  '/document.featurePolicy': typeof DocumentDotfeaturePolicyRoute
  '/document.featurePolicy.allowedFeatures()': typeof DocumentDotfeaturePolicyDotallowedFeaturesRoute
  '/document.featurePolicy.features()': typeof DocumentDotfeaturePolicyDotfeaturesRoute
  '/navigator': typeof NavigatorRoute
  '/navigator.clipboard': typeof NavigatorDotclipboardRoute
  '/navigator.connection': typeof NavigatorDotconnectionRoute
  '/navigator.geolocation.getCurrentPosition()': typeof NavigatorDotgeolocationDotgetCurrentPositionRoute
  '/navigator.getBattery()': typeof NavigatorDotgetBatteryRoute
  '/navigator.keyboard': typeof NavigatorDotkeyboardRoute
  '/navigator.keyboard.getLayoutMap()': typeof NavigatorDotkeyboardDotgetLayoutMapRoute
  '/navigator.mediaDevices': typeof NavigatorDotmediaDevicesRoute
  '/navigator.mediaDevices.enumerateDevices()': typeof NavigatorDotmediaDevicesDotenumerateDevicesRoute
  '/navigator.mediaDevices.getSupportedConstraints()': typeof NavigatorDotmediaDevicesDotgetSupportedConstraintsRoute
  '/navigator.onLine': typeof NavigatorDotonLineRoute
  '/navigator.share()': typeof NavigatorDotshareRoute
  '/navigator.storage': typeof NavigatorDotstorageRoute
  '/navigator.storage.estimate()': typeof NavigatorDotstorageDotestimateRoute
  '/navigator.userActivation': typeof NavigatorDotuserActivationRoute
  '/navigator.wakeLock': typeof NavigatorDotwakeLockRoute
  '/useLocation()': typeof UseLocationRoute
  '/useRouter()': typeof UseRouterRoute
  '/useRouterState()': typeof UseRouterStateRoute
  '/window': typeof WindowRoute
  '/window.getScreenDetails()': typeof WindowDotgetScreenDetailsRoute
  '/window.performance': typeof WindowDotperformanceRoute
  '/window.queryLocalFonts()': typeof WindowDotqueryLocalFontsRoute
  '/window.screen': typeof WindowDotscreenRoute
  '/window.viewport': typeof WindowDotviewportRoute
  '/window.visualViewport': typeof WindowDotvisualViewportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Image()': typeof ImageRoute
  '/Math.random()': typeof MathDotrandomRoute
  '/document': typeof DocumentRoute
  '/document.featurePolicy': typeof DocumentDotfeaturePolicyRoute
  '/document.featurePolicy.allowedFeatures()': typeof DocumentDotfeaturePolicyDotallowedFeaturesRoute
  '/document.featurePolicy.features()': typeof DocumentDotfeaturePolicyDotfeaturesRoute
  '/navigator': typeof NavigatorRoute
  '/navigator.clipboard': typeof NavigatorDotclipboardRoute
  '/navigator.connection': typeof NavigatorDotconnectionRoute
  '/navigator.geolocation.getCurrentPosition()': typeof NavigatorDotgeolocationDotgetCurrentPositionRoute
  '/navigator.getBattery()': typeof NavigatorDotgetBatteryRoute
  '/navigator.keyboard': typeof NavigatorDotkeyboardRoute
  '/navigator.keyboard.getLayoutMap()': typeof NavigatorDotkeyboardDotgetLayoutMapRoute
  '/navigator.mediaDevices': typeof NavigatorDotmediaDevicesRoute
  '/navigator.mediaDevices.enumerateDevices()': typeof NavigatorDotmediaDevicesDotenumerateDevicesRoute
  '/navigator.mediaDevices.getSupportedConstraints()': typeof NavigatorDotmediaDevicesDotgetSupportedConstraintsRoute
  '/navigator.onLine': typeof NavigatorDotonLineRoute
  '/navigator.share()': typeof NavigatorDotshareRoute
  '/navigator.storage': typeof NavigatorDotstorageRoute
  '/navigator.storage.estimate()': typeof NavigatorDotstorageDotestimateRoute
  '/navigator.userActivation': typeof NavigatorDotuserActivationRoute
  '/navigator.wakeLock': typeof NavigatorDotwakeLockRoute
  '/useLocation()': typeof UseLocationRoute
  '/useRouter()': typeof UseRouterRoute
  '/useRouterState()': typeof UseRouterStateRoute
  '/window': typeof WindowRoute
  '/window.getScreenDetails()': typeof WindowDotgetScreenDetailsRoute
  '/window.performance': typeof WindowDotperformanceRoute
  '/window.queryLocalFonts()': typeof WindowDotqueryLocalFontsRoute
  '/window.screen': typeof WindowDotscreenRoute
  '/window.viewport': typeof WindowDotviewportRoute
  '/window.visualViewport': typeof WindowDotvisualViewportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Image()': typeof ImageRoute
  '/Math.random()': typeof MathDotrandomRoute
  '/document': typeof DocumentRoute
  '/document.featurePolicy': typeof DocumentDotfeaturePolicyRoute
  '/document.featurePolicy.allowedFeatures()': typeof DocumentDotfeaturePolicyDotallowedFeaturesRoute
  '/document.featurePolicy.features()': typeof DocumentDotfeaturePolicyDotfeaturesRoute
  '/navigator': typeof NavigatorRoute
  '/navigator.clipboard': typeof NavigatorDotclipboardRoute
  '/navigator.connection': typeof NavigatorDotconnectionRoute
  '/navigator.geolocation.getCurrentPosition()': typeof NavigatorDotgeolocationDotgetCurrentPositionRoute
  '/navigator.getBattery()': typeof NavigatorDotgetBatteryRoute
  '/navigator.keyboard': typeof NavigatorDotkeyboardRoute
  '/navigator.keyboard.getLayoutMap()': typeof NavigatorDotkeyboardDotgetLayoutMapRoute
  '/navigator.mediaDevices': typeof NavigatorDotmediaDevicesRoute
  '/navigator.mediaDevices.enumerateDevices()': typeof NavigatorDotmediaDevicesDotenumerateDevicesRoute
  '/navigator.mediaDevices.getSupportedConstraints()': typeof NavigatorDotmediaDevicesDotgetSupportedConstraintsRoute
  '/navigator.onLine': typeof NavigatorDotonLineRoute
  '/navigator.share()': typeof NavigatorDotshareRoute
  '/navigator.storage': typeof NavigatorDotstorageRoute
  '/navigator.storage.estimate()': typeof NavigatorDotstorageDotestimateRoute
  '/navigator.userActivation': typeof NavigatorDotuserActivationRoute
  '/navigator.wakeLock': typeof NavigatorDotwakeLockRoute
  '/useLocation()': typeof UseLocationRoute
  '/useRouter()': typeof UseRouterRoute
  '/useRouterState()': typeof UseRouterStateRoute
  '/window': typeof WindowRoute
  '/window.getScreenDetails()': typeof WindowDotgetScreenDetailsRoute
  '/window.performance': typeof WindowDotperformanceRoute
  '/window.queryLocalFonts()': typeof WindowDotqueryLocalFontsRoute
  '/window.screen': typeof WindowDotscreenRoute
  '/window.viewport': typeof WindowDotviewportRoute
  '/window.visualViewport': typeof WindowDotvisualViewportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Image()'
    | '/Math.random()'
    | '/document'
    | '/document.featurePolicy'
    | '/document.featurePolicy.allowedFeatures()'
    | '/document.featurePolicy.features()'
    | '/navigator'
    | '/navigator.clipboard'
    | '/navigator.connection'
    | '/navigator.geolocation.getCurrentPosition()'
    | '/navigator.getBattery()'
    | '/navigator.keyboard'
    | '/navigator.keyboard.getLayoutMap()'
    | '/navigator.mediaDevices'
    | '/navigator.mediaDevices.enumerateDevices()'
    | '/navigator.mediaDevices.getSupportedConstraints()'
    | '/navigator.onLine'
    | '/navigator.share()'
    | '/navigator.storage'
    | '/navigator.storage.estimate()'
    | '/navigator.userActivation'
    | '/navigator.wakeLock'
    | '/useLocation()'
    | '/useRouter()'
    | '/useRouterState()'
    | '/window'
    | '/window.getScreenDetails()'
    | '/window.performance'
    | '/window.queryLocalFonts()'
    | '/window.screen'
    | '/window.viewport'
    | '/window.visualViewport'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Image()'
    | '/Math.random()'
    | '/document'
    | '/document.featurePolicy'
    | '/document.featurePolicy.allowedFeatures()'
    | '/document.featurePolicy.features()'
    | '/navigator'
    | '/navigator.clipboard'
    | '/navigator.connection'
    | '/navigator.geolocation.getCurrentPosition()'
    | '/navigator.getBattery()'
    | '/navigator.keyboard'
    | '/navigator.keyboard.getLayoutMap()'
    | '/navigator.mediaDevices'
    | '/navigator.mediaDevices.enumerateDevices()'
    | '/navigator.mediaDevices.getSupportedConstraints()'
    | '/navigator.onLine'
    | '/navigator.share()'
    | '/navigator.storage'
    | '/navigator.storage.estimate()'
    | '/navigator.userActivation'
    | '/navigator.wakeLock'
    | '/useLocation()'
    | '/useRouter()'
    | '/useRouterState()'
    | '/window'
    | '/window.getScreenDetails()'
    | '/window.performance'
    | '/window.queryLocalFonts()'
    | '/window.screen'
    | '/window.viewport'
    | '/window.visualViewport'
  id:
    | '__root__'
    | '/'
    | '/Image()'
    | '/Math.random()'
    | '/document'
    | '/document.featurePolicy'
    | '/document.featurePolicy.allowedFeatures()'
    | '/document.featurePolicy.features()'
    | '/navigator'
    | '/navigator.clipboard'
    | '/navigator.connection'
    | '/navigator.geolocation.getCurrentPosition()'
    | '/navigator.getBattery()'
    | '/navigator.keyboard'
    | '/navigator.keyboard.getLayoutMap()'
    | '/navigator.mediaDevices'
    | '/navigator.mediaDevices.enumerateDevices()'
    | '/navigator.mediaDevices.getSupportedConstraints()'
    | '/navigator.onLine'
    | '/navigator.share()'
    | '/navigator.storage'
    | '/navigator.storage.estimate()'
    | '/navigator.userActivation'
    | '/navigator.wakeLock'
    | '/useLocation()'
    | '/useRouter()'
    | '/useRouterState()'
    | '/window'
    | '/window.getScreenDetails()'
    | '/window.performance'
    | '/window.queryLocalFonts()'
    | '/window.screen'
    | '/window.viewport'
    | '/window.visualViewport'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImageRoute: typeof ImageRoute
  MathDotrandomRoute: typeof MathDotrandomRoute
  DocumentRoute: typeof DocumentRoute
  DocumentDotfeaturePolicyRoute: typeof DocumentDotfeaturePolicyRoute
  DocumentDotfeaturePolicyDotallowedFeaturesRoute: typeof DocumentDotfeaturePolicyDotallowedFeaturesRoute
  DocumentDotfeaturePolicyDotfeaturesRoute: typeof DocumentDotfeaturePolicyDotfeaturesRoute
  NavigatorRoute: typeof NavigatorRoute
  NavigatorDotclipboardRoute: typeof NavigatorDotclipboardRoute
  NavigatorDotconnectionRoute: typeof NavigatorDotconnectionRoute
  NavigatorDotgeolocationDotgetCurrentPositionRoute: typeof NavigatorDotgeolocationDotgetCurrentPositionRoute
  NavigatorDotgetBatteryRoute: typeof NavigatorDotgetBatteryRoute
  NavigatorDotkeyboardRoute: typeof NavigatorDotkeyboardRoute
  NavigatorDotkeyboardDotgetLayoutMapRoute: typeof NavigatorDotkeyboardDotgetLayoutMapRoute
  NavigatorDotmediaDevicesRoute: typeof NavigatorDotmediaDevicesRoute
  NavigatorDotmediaDevicesDotenumerateDevicesRoute: typeof NavigatorDotmediaDevicesDotenumerateDevicesRoute
  NavigatorDotmediaDevicesDotgetSupportedConstraintsRoute: typeof NavigatorDotmediaDevicesDotgetSupportedConstraintsRoute
  NavigatorDotonLineRoute: typeof NavigatorDotonLineRoute
  NavigatorDotshareRoute: typeof NavigatorDotshareRoute
  NavigatorDotstorageRoute: typeof NavigatorDotstorageRoute
  NavigatorDotstorageDotestimateRoute: typeof NavigatorDotstorageDotestimateRoute
  NavigatorDotuserActivationRoute: typeof NavigatorDotuserActivationRoute
  NavigatorDotwakeLockRoute: typeof NavigatorDotwakeLockRoute
  UseLocationRoute: typeof UseLocationRoute
  UseRouterRoute: typeof UseRouterRoute
  UseRouterStateRoute: typeof UseRouterStateRoute
  WindowRoute: typeof WindowRoute
  WindowDotgetScreenDetailsRoute: typeof WindowDotgetScreenDetailsRoute
  WindowDotperformanceRoute: typeof WindowDotperformanceRoute
  WindowDotqueryLocalFontsRoute: typeof WindowDotqueryLocalFontsRoute
  WindowDotscreenRoute: typeof WindowDotscreenRoute
  WindowDotviewportRoute: typeof WindowDotviewportRoute
  WindowDotvisualViewportRoute: typeof WindowDotvisualViewportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/window.visualViewport': {
      id: '/window.visualViewport'
      path: '/window.visualViewport'
      fullPath: '/window.visualViewport'
      preLoaderRoute: typeof WindowDotvisualViewportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window.viewport': {
      id: '/window.viewport'
      path: '/window.viewport'
      fullPath: '/window.viewport'
      preLoaderRoute: typeof WindowDotviewportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window.screen': {
      id: '/window.screen'
      path: '/window.screen'
      fullPath: '/window.screen'
      preLoaderRoute: typeof WindowDotscreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window.queryLocalFonts()': {
      id: '/window.queryLocalFonts()'
      path: '/window.queryLocalFonts()'
      fullPath: '/window.queryLocalFonts()'
      preLoaderRoute: typeof WindowDotqueryLocalFontsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window.performance': {
      id: '/window.performance'
      path: '/window.performance'
      fullPath: '/window.performance'
      preLoaderRoute: typeof WindowDotperformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window.getScreenDetails()': {
      id: '/window.getScreenDetails()'
      path: '/window.getScreenDetails()'
      fullPath: '/window.getScreenDetails()'
      preLoaderRoute: typeof WindowDotgetScreenDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window': {
      id: '/window'
      path: '/window'
      fullPath: '/window'
      preLoaderRoute: typeof WindowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/useRouterState()': {
      id: '/useRouterState()'
      path: '/useRouterState()'
      fullPath: '/useRouterState()'
      preLoaderRoute: typeof UseRouterStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/useRouter()': {
      id: '/useRouter()'
      path: '/useRouter()'
      fullPath: '/useRouter()'
      preLoaderRoute: typeof UseRouterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/useLocation()': {
      id: '/useLocation()'
      path: '/useLocation()'
      fullPath: '/useLocation()'
      preLoaderRoute: typeof UseLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigator.wakeLock': {
      id: '/navigator.wakeLock'
      path: '/navigator.wakeLock'
      fullPath: '/navigator.wakeLock'
      preLoaderRoute: typeof NavigatorDotwakeLockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigator.userActivation': {
      id: '/navigator.userActivation'
      path: '/navigator.userActivation'
      fullPath: '/navigator.userActivation'
      preLoaderRoute: typeof NavigatorDotuserActivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigator.storage.estimate()': {
      id: '/navigator.storage.estimate()'
      path: '/navigator.storage.estimate()'
      fullPath: '/navigator.storage.estimate()'
      preLoaderRoute: typeof NavigatorDotstorageDotestimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigator.storage': {
      id: '/navigator.storage'
      path: '/navigator.storage'
      fullPath: '/navigator.storage'
      preLoaderRoute: typeof NavigatorDotstorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigator.share()': {
      id: '/navigator.share()'
      path: '/navigator.share()'
      fullPath: '/navigator.share()'
      preLoaderRoute: typeof NavigatorDotshareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigator.onLine': {
      id: '/navigator.onLine'
      path: '/navigator.onLine'
      fullPath: '/navigator.onLine'
      preLoaderRoute: typeof NavigatorDotonLineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigator.mediaDevices.getSupportedConstraints()': {
      id: '/navigator.mediaDevices.getSupportedConstraints()'
      path: '/navigator.mediaDevices.getSupportedConstraints()'
      fullPath: '/navigator.mediaDevices.getSupportedConstraints()'
      preLoaderRoute: typeof NavigatorDotmediaDevicesDotgetSupportedConstraintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigator.mediaDevices.enumerateDevices()': {
      id: '/navigator.mediaDevices.enumerateDevices()'
      path: '/navigator.mediaDevices.enumerateDevices()'
      fullPath: '/navigator.mediaDevices.enumerateDevices()'
      preLoaderRoute: typeof NavigatorDotmediaDevicesDotenumerateDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigator.mediaDevices': {
      id: '/navigator.mediaDevices'
      path: '/navigator.mediaDevices'
      fullPath: '/navigator.mediaDevices'
      preLoaderRoute: typeof NavigatorDotmediaDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigator.keyboard.getLayoutMap()': {
      id: '/navigator.keyboard.getLayoutMap()'
      path: '/navigator.keyboard.getLayoutMap()'
      fullPath: '/navigator.keyboard.getLayoutMap()'
      preLoaderRoute: typeof NavigatorDotkeyboardDotgetLayoutMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigator.keyboard': {
      id: '/navigator.keyboard'
      path: '/navigator.keyboard'
      fullPath: '/navigator.keyboard'
      preLoaderRoute: typeof NavigatorDotkeyboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigator.getBattery()': {
      id: '/navigator.getBattery()'
      path: '/navigator.getBattery()'
      fullPath: '/navigator.getBattery()'
      preLoaderRoute: typeof NavigatorDotgetBatteryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigator.geolocation.getCurrentPosition()': {
      id: '/navigator.geolocation.getCurrentPosition()'
      path: '/navigator.geolocation.getCurrentPosition()'
      fullPath: '/navigator.geolocation.getCurrentPosition()'
      preLoaderRoute: typeof NavigatorDotgeolocationDotgetCurrentPositionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigator.connection': {
      id: '/navigator.connection'
      path: '/navigator.connection'
      fullPath: '/navigator.connection'
      preLoaderRoute: typeof NavigatorDotconnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigator.clipboard': {
      id: '/navigator.clipboard'
      path: '/navigator.clipboard'
      fullPath: '/navigator.clipboard'
      preLoaderRoute: typeof NavigatorDotclipboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigator': {
      id: '/navigator'
      path: '/navigator'
      fullPath: '/navigator'
      preLoaderRoute: typeof NavigatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document.featurePolicy.features()': {
      id: '/document.featurePolicy.features()'
      path: '/document.featurePolicy.features()'
      fullPath: '/document.featurePolicy.features()'
      preLoaderRoute: typeof DocumentDotfeaturePolicyDotfeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document.featurePolicy.allowedFeatures()': {
      id: '/document.featurePolicy.allowedFeatures()'
      path: '/document.featurePolicy.allowedFeatures()'
      fullPath: '/document.featurePolicy.allowedFeatures()'
      preLoaderRoute: typeof DocumentDotfeaturePolicyDotallowedFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document.featurePolicy': {
      id: '/document.featurePolicy'
      path: '/document.featurePolicy'
      fullPath: '/document.featurePolicy'
      preLoaderRoute: typeof DocumentDotfeaturePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document': {
      id: '/document'
      path: '/document'
      fullPath: '/document'
      preLoaderRoute: typeof DocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Math.random()': {
      id: '/Math.random()'
      path: '/Math.random()'
      fullPath: '/Math.random()'
      preLoaderRoute: typeof MathDotrandomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Image()': {
      id: '/Image()'
      path: '/Image()'
      fullPath: '/Image()'
      preLoaderRoute: typeof ImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImageRoute: ImageRoute,
  MathDotrandomRoute: MathDotrandomRoute,
  DocumentRoute: DocumentRoute,
  DocumentDotfeaturePolicyRoute: DocumentDotfeaturePolicyRoute,
  DocumentDotfeaturePolicyDotallowedFeaturesRoute:
    DocumentDotfeaturePolicyDotallowedFeaturesRoute,
  DocumentDotfeaturePolicyDotfeaturesRoute:
    DocumentDotfeaturePolicyDotfeaturesRoute,
  NavigatorRoute: NavigatorRoute,
  NavigatorDotclipboardRoute: NavigatorDotclipboardRoute,
  NavigatorDotconnectionRoute: NavigatorDotconnectionRoute,
  NavigatorDotgeolocationDotgetCurrentPositionRoute:
    NavigatorDotgeolocationDotgetCurrentPositionRoute,
  NavigatorDotgetBatteryRoute: NavigatorDotgetBatteryRoute,
  NavigatorDotkeyboardRoute: NavigatorDotkeyboardRoute,
  NavigatorDotkeyboardDotgetLayoutMapRoute:
    NavigatorDotkeyboardDotgetLayoutMapRoute,
  NavigatorDotmediaDevicesRoute: NavigatorDotmediaDevicesRoute,
  NavigatorDotmediaDevicesDotenumerateDevicesRoute:
    NavigatorDotmediaDevicesDotenumerateDevicesRoute,
  NavigatorDotmediaDevicesDotgetSupportedConstraintsRoute:
    NavigatorDotmediaDevicesDotgetSupportedConstraintsRoute,
  NavigatorDotonLineRoute: NavigatorDotonLineRoute,
  NavigatorDotshareRoute: NavigatorDotshareRoute,
  NavigatorDotstorageRoute: NavigatorDotstorageRoute,
  NavigatorDotstorageDotestimateRoute: NavigatorDotstorageDotestimateRoute,
  NavigatorDotuserActivationRoute: NavigatorDotuserActivationRoute,
  NavigatorDotwakeLockRoute: NavigatorDotwakeLockRoute,
  UseLocationRoute: UseLocationRoute,
  UseRouterRoute: UseRouterRoute,
  UseRouterStateRoute: UseRouterStateRoute,
  WindowRoute: WindowRoute,
  WindowDotgetScreenDetailsRoute: WindowDotgetScreenDetailsRoute,
  WindowDotperformanceRoute: WindowDotperformanceRoute,
  WindowDotqueryLocalFontsRoute: WindowDotqueryLocalFontsRoute,
  WindowDotscreenRoute: WindowDotscreenRoute,
  WindowDotviewportRoute: WindowDotviewportRoute,
  WindowDotvisualViewportRoute: WindowDotvisualViewportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
